trigger:
  paths:
    exclude:
    - /README.md

name: '$(date:yyyy)$(date:.MM)$(date:.dd)$(rev:.r)'

jobs:
- job: Job_1
  displayName: Build and Pack SHAPE.Data.District.Shared NuGet
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: '**/*.csproj'
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '**/*.csproj'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*.Tests.csproj'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/Futilities.Outright.csproj'
      nobuild: true
      includesymbols: true
      includesource: true
      versioningScheme: 'byBuildNumber'
